-- ============================================================================
-- 24-Hour Command Center — Supabase Schema
-- Run this once in your Supabase project's SQL Editor (Project -> SQL Editor
-- -> New query -> paste all of this -> Run). Safe to re-run (uses IF NOT EXISTS
-- / CREATE OR REPLACE wherever possible).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. TASKS  (one row per scheduled clock-wedge / task card)
-- ---------------------------------------------------------------------------
create table if not exists public.tasks (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date         date not null,
  label        text not null default 'Untitled Task',
  goal         text default 'Uncategorized',
  start_time   text not null,               -- "HH:MM" 24h
  end_time     text not null,               -- "HH:MM" 24h
  color        text default '#4a6984',
  notes        text,
  completed    boolean not null default false,
  subtasks     jsonb not null default '[]'::jsonb,   -- [{ text, done }]
  review       text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists tasks_user_date_idx on public.tasks(user_id, date);

-- ---------------------------------------------------------------------------
-- 2. GOALS  (master goals used to tag/group tasks)
-- ---------------------------------------------------------------------------
create table if not exists public.goals (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name         text not null,
  color        text default '#4a6984',   -- "Goal Ink" color, synced across devices
  created_at   timestamptz not null default now(),
  unique (user_id, name)
);
-- Safety net if you already ran an earlier version of this script without the color column:
alter table public.goals add column if not exists color text default '#4a6984';

-- ---------------------------------------------------------------------------
-- 3. MILESTONES  (roadmap items per goal)
-- ---------------------------------------------------------------------------
create table if not exists public.milestones (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  goal         text not null,
  text         text not null,
  done         boolean not null default false,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now()
);
create index if not exists milestones_user_goal_idx on public.milestones(user_id, goal);

-- ---------------------------------------------------------------------------
-- 4. BACKLOG ITEMS  (the "Idea Inbox")
-- ---------------------------------------------------------------------------
create table if not exists public.backlog_items (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  label        text not null,
  goal         text default 'Uncategorized',
  notes        text,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 5. DAILY JOURNALS  (one row per user per date)
-- ---------------------------------------------------------------------------
create table if not exists public.daily_journals (
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date         date not null,
  content      text,
  updated_at   timestamptz not null default now(),
  primary key (user_id, date)
);

-- ---------------------------------------------------------------------------
-- 6. MASTER JOURNAL  (single long-running entry per user)
-- ---------------------------------------------------------------------------
create table if not exists public.master_journal (
  user_id      uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  content      text,
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 7. USER SETTINGS  (Gemini API key + model, follows the user across devices)
-- ---------------------------------------------------------------------------
create table if not exists public.user_settings (
  user_id         uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  gemini_api_key  text,
  gemini_model    text default 'gemini-3.6-flash',
  updated_at      timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 8. updated_at auto-maintenance
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tasks_updated on public.tasks;
create trigger trg_tasks_updated before update on public.tasks
for each row execute function public.set_updated_at();

drop trigger if exists trg_daily_journals_updated on public.daily_journals;
create trigger trg_daily_journals_updated before update on public.daily_journals
for each row execute function public.set_updated_at();

drop trigger if exists trg_master_journal_updated on public.master_journal;
create trigger trg_master_journal_updated before update on public.master_journal
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_settings_updated on public.user_settings;
create trigger trg_user_settings_updated before update on public.user_settings
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 9. Row Level Security — every user can only ever see/write their own rows
-- ---------------------------------------------------------------------------
alter table public.tasks          enable row level security;
alter table public.goals          enable row level security;
alter table public.milestones     enable row level security;
alter table public.backlog_items  enable row level security;
alter table public.daily_journals enable row level security;
alter table public.master_journal enable row level security;
alter table public.user_settings  enable row level security;

drop policy if exists "Individual access" on public.tasks;
create policy "Individual access" on public.tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Individual access" on public.goals;
create policy "Individual access" on public.goals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Individual access" on public.milestones;
create policy "Individual access" on public.milestones
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Individual access" on public.backlog_items;
create policy "Individual access" on public.backlog_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Individual access" on public.daily_journals;
create policy "Individual access" on public.daily_journals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Individual access" on public.master_journal;
create policy "Individual access" on public.master_journal
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Individual access" on public.user_settings;
create policy "Individual access" on public.user_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 10. Realtime — so a change on one device shows up live on another.
--     (If this errors saying the table is already a member, that's fine —
--     it just means it's already enabled.)
-- ---------------------------------------------------------------------------
alter publication supabase_realtime add table
  public.tasks,
  public.goals,
  public.milestones,
  public.backlog_items,
  public.daily_journals,
  public.master_journal;

-- ============================================================================
-- Done. Next: Project Settings -> API -> copy "Project URL" and the
-- "anon public" key into the app's Cloud Sync panel.
-- ============================================================================
